import level

#Note
note = "generated by gap_gen.py"

#Settings
title = "The Pit"
width = 3840
height = 2160

mirrored = True

#Init
lev = level.Level(title, width, height, mirrored)

'''
Killing floor
'''
lev.add_kill_box(-10*width, 11*width, height + 300, 2*height, mirror=False)

'''
Plats / Walls
'''
def build_box(x, y, w, h):
    lev.add_obstacle(x, x + w, y, y + h)

PLAT_TH = 50

def build_plat(x, y, w):
    build_box(x, y, w, PLAT_TH)

WALL_TH = 50

def build_wall(x, y, h):
    build_box(x, y, WALL_TH, h)


#Towers
PLAT_CEIL = 1100

PLAT_H = 250
PLAT_X = 200
PLAT_W = 250

PLAT_OFFSET = 500
PLAT_TILT = 200

NUM_PLATS = 3

#Staircase
for i in range(NUM_PLATS):
    build_plat(PLAT_X + (PLAT_W + PLAT_OFFSET)*(i%2) + PLAT_TILT * i, PLAT_CEIL + PLAT_H * (i), PLAT_W)
    lev.add_box_spawn(PLAT_X + (PLAT_W + PLAT_OFFSET)*(i%2) + PLAT_TILT * i + PLAT_W/2.0, PLAT_CEIL + PLAT_H * (i) - 60, ["rocket"], rd=1200)

#Center
CENTER_W = 300
CENTER_H = PLAT_CEIL + 600
build_plat(width/2 - CENTER_W/2, CENTER_H, CENTER_W)

'''
Spawns
'''
SPAWN_H = 500

SPAWN_X = width/8
DIFF = width/4

build_plat(SPAWN_X, SPAWN_H, PLAT_W)
build_plat(SPAWN_X + DIFF, SPAWN_H, PLAT_W)

#For now, all clustered on same plats
for i in range(2):
    lev.add_player_spawn(SPAWN_X + PLAT_W/2 + i * DIFF, SPAWN_H - 60)



# for i in range(2):
#     lev.add_player_spawn(width/2 + (CENTER_W/4 * (1 if i%2 > 0 else -1)), CENTER_H - 60, mirror=False)

'''
Weapons
'''
lev.add_box_spawn(width/2, CENTER_H - 60, ["rocket"], mirror=False)

'''
Background
'''
sky = "sunset"
pit = "refuge_tower"
shadow = "shadow"

lev.add_background(sky, -width, width*2, -height/2, height * 2)
lev.add_background(pit, -width, width*2, SPAWN_H, height * 2)
lev.add_background(shadow, -width, width*2, SPAWN_H - 5, 5*height/4)

print "Saving complex..."
lev.save("../the_gap.json", note = note)
