import level
from pre_builts import build_box

#Note
note = "generated by platforms_gen.py"

#Settings
title = "Platforms"
width = 3840
height = 2160

mirrored = True

#Init
lev = level.Level(title, width, height, mirrored)

'''
Killing floor
'''
lev.add_kill_box(-10*width, 11*width, height + 100, 2*height, mirror=False)

'''
Plats / Walls
'''
PLAT_TH = 30

def bb(x, y, w, h, mirror=None, pierceable=None):
    build_box(lev, x, y, w, h, mirror=mirror, pierceable=pierceable)

def build_plat(x, y, w, mirror=None, pierceable=None):
    bb(x, y, w, PLAT_TH, mirror=mirror, pierceable=pierceable)

PLAT_W =400
PLAT_X_SEP = 300
PLAT_Y_SEP = 280

center_x = width/2
center_y = 2*height/3

build_plat(center_x - PLAT_X_SEP/2 - PLAT_W/2, center_y, PLAT_W)

build_plat(center_x, center_y - PLAT_Y_SEP/2 - PLAT_TH/2, PLAT_W, mirror = False)
build_plat(center_x, center_y + PLAT_Y_SEP/2 + PLAT_TH/2, PLAT_W, mirror = False)

'''
Spawns
'''

for i in range(2):
    lev.add_player_spawn(center_x - PLAT_X_SEP/2 - PLAT_W/2  + (-1 if (i%2 == 0) else 1), center_y - 80)


'''
Weapons
'''
lev.add_box_spawn(center_x - PLAT_W/4, center_y - PLAT_Y_SEP/2 - PLAT_TH/2 - 60, ["pierce", "flame", "rocket", "bounce"])
lev.add_box_spawn(center_x - PLAT_W/4, center_y + PLAT_Y_SEP/2 + PLAT_TH/2 - 60, ["pierce", "flame", "rocket", "bounce"])

print "Saving level..."
lev.save("../platforms.json", note = note)