import level

lev = level.Level("test", 1280, 720)

for i in range(4):
    lev.add_player_spawn(50 + i%2 * 200, 50 + i%2 * 300)

lev.add_obstacle(-20, 1300, 700, 740)
lev.add_obstacle(-20, 1300, -20, 20)

lev.add_obstacle(-20, 20, -20, 740)
lev.add_obstacle(1260, 1300, -20, 740)

lev.add_box_spawn(640, 360, ["rocket", "flame", "pierce", "bounce"])

lev.save("../test.json", note = "generated by test_gen.py")

